### ISSUE TITLE
Adding color to highlight Value names?

### ISSUE THREAD

**Issue by mcFactor** [nkristek/Highlight#5]
How about having a color for value names highlighting? At the moment names are highlighted as strings...
Nice quick library BTW. Thanks.

**Comment by nkristek** [comment]
Hello and thank you for trying out this library! I want to clarify what you've asked, are you talking about number values in JSON? For this, there is [`numericValueColor`](https://github.com/nkristek/Highlight/blob/9b29aa54d09f298705c220ce44d8557addd96a6b/Sources/Highlight/DefaultJsonSyntaxHighlightingTheme.swift#L23) and [`numericValueFont`](https://github.com/nkristek/Highlight/blob/9b29aa54d09f298705c220ce44d8557addd96a6b/Sources/Highlight/DefaultJsonSyntaxHighlightingTheme.swift#L25) which will result in the following output:
| Light | Dark |
| --- | --- |
| <img width="147" alt="Screen Shot 2021-05-06 at 09 40 18" src="https://user-images.githubusercontent.com/12814701/117260171-17360e00-ae4f-11eb-9f8d-751351842f75.png"> | <img width="150" alt="Screen Shot 2021-05-06 at 09 40 03" src="https://user-images.githubusercontent.com/12814701/117260182-1a30fe80-ae4f-11eb-9989-1a7862ac51fc.png"> |

**Comment by nkristek** [comment]
Or are you talking about the `"number"` string on left side of the colon?

**Comment by nkristek** [comment]
Is this issue solved by #6? I've just released version [0.4](https://github.com/nkristek/Highlight/releases/tag/0.4.0) which includes that change.

**Comment by nkristek** [comment]
Please reopen this issue if it still persists.
